In [14]:
import pandas as pd
import numpy as np


In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score , roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split , GridSearchCV


In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
data = pd.read_csv(r"C:\Users\lenovo\Downloads\dataset\winequality-red.csv")
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1591            6.2             0.600         0.08             2.0      0.090   
1592            5.9             0.550         0.10             2.2      0.062   
1593            6.3             0.510         0.13             2.3      0.076   
1594            5.9             0.645         0.12             2.0      0.075   
1595            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1591                 32.0                  44.0  0.99490  3.45       0.58   
1592                 39.0                  51.0  0.99512  3.52       0.76   
1593                 29.0                  40.0  0.99574  3.42       0.75   
1594                 32.0                  44.0  0.99547  3.57       0.71   
1595                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1591     10.5        5  
1592     11.2        6  
1593     11.0        6  
1594     10.2        5  
1595     11.0        6  

[1596 rows x 12 columns]

In [18]:
x= data.iloc[:,:-1]
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1591            6.2             0.600         0.08             2.0      0.090   
1592            5.9             0.550         0.10             2.2      0.062   
1593            6.3             0.510         0.13             2.3      0.076   
1594            5.9             0.645         0.12             2.0      0.075   
1595            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1591                 32.0                  44.0  0.99490  3.45       0.58   
1592                 39.0                  51.0  0.99512  3.52       0.76   
1593                 29.0                  40.0  0.99574  3.42       0.75   
1594                 32.0                  44.0  0.99547  3.57       0.71   
1595                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1591     10.5  
1592     11.2  
1593     11.0  
1594     10.2  
1595     11.0  

[1596 rows x 11 columns]

In [19]:
y= data.iloc[:,-1]
y

0       5
1       5
2       5
3       6
4       5
       ..
1591    5
1592    6
1593    6
1594    5
1595    6
Name: quality, Length: 1596, dtype: int64

In [20]:
x_train, x_test, y_train, y_test  =train_test_split(x,y,random_state=111)      ## by defoult data 75 and 25. 75 iss training data and 25 is testing data 

In [21]:
knn = KNeighborsClassifier()

In [22]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [23]:
knn.score(x_test, y_test)*100

47.61904761904761

### improu the accuracy

In [24]:
pram = { 
    "n_neighbors":[3,5,7,9,12,13,15,17,21],
    "algorithm":['auto', "ball_tree", "kd_tree", "brute"],
    "leaf_size":[10, 15, 20, 25, 30, 35, 45, 50 ],
    "p":[1,2],
    "weights" : ["uniform", "distance"]
}

In [25]:
grid_cv = GridSearchCV(knn,param_grid=pram)

In [26]:
grid_cv.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 15, 20, 25, 30, 35, 45, 50],
                         'n_neighbors': [3, 5, 7, 9, 12, 13, 15, 17, 21],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [ ]:
grid_cv.best_params_

In [32]:
knn=KNeighborsClassifier(n_neighbors=15,p=1,weights='distance',leaf_size=10, algorithm='auto')

In [33]:
knn.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=15, p=1, weights='distance')

In [34]:
knn.score(x_test,y_test)*100

0.6390977443609023

In [35]:
import pickle
pickle.dump(knn, open("knn.pkl" , "wb"))

In [36]:
pwd

'D:\\ESD\\Krish Nike'

In [37]:
ls

 Volume in drive D is New Volume
 Volume Serial Number is CC8D-D0AC

 Directory of D:\ESD\Krish Nike

11/19/2022  11:18 AM    <DIR>          .
11/19/2022  11:18 AM    <DIR>          ..
11/17/2022  11:29 PM    <DIR>          .ipynb_checkpoints
11/18/2022  09:31 AM        11,900,224 Decision tree 1.ipynb
11/14/2022  01:55 PM        11,149,022 Decision tree.ipynb
11/15/2022  10:57 PM           135,770 df1_model.png
11/14/2022  12:17 PM            48,999 dt_en-meta.dot
11/18/2022  02:17 PM         1,069,972 Grid Search, Bagging classifier Random forest.ipynb
11/19/2022  11:18 AM            59,493 KNN , SVM , SVR , Stacking.web.ipynb
11/19/2022  11:19 AM           147,561 knn.pkl
11/14/2022  10:32 AM           825,342 Linear Regression of ml.ipynb
11/14/2022  10:52 AM        37,869,158 logistic regression.ipynb
11/17/2022  10:59 AM             7,932 Untitled.ipynb
10/18/2022  12:33 PM             7,046 Untitled1.ipynb
              11 File(s)     63,220,519 bytes
               3 Dir(s)  11

In [38]:
knn.predict([x_test.iloc[0]])

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([6], dtype=int64)

In [39]:
x_test.iloc[0]

fixed acidity           11.30000
volatile acidity         0.36000
citric acid              0.66000
residual sugar           2.40000
chlorides                0.12300
free sulfur dioxide      3.00000
total sulfur dioxide     8.00000
density                  0.99642
pH                       3.20000
sulphates                0.53000
alcohol                 11.90000
Name: 1017, dtype: float64

### SVM

In [40]:
from sklearn.svm import SVC

In [41]:
svc=SVC()

In [42]:
svc.fit(x_train,y_train)

SVC()

In [43]:
svc.score(x_test,y_test)

0.506265664160401

In [44]:
pram= { 
    "kernel":['linear','poly','rbf','sigmoid'],
    "C":[.1, .4, .6, 1, 3,100,200,500],
    "gamma":[.001,.1,.4,.004,.003]
    
}

In [48]:
svm_grid=GridSearchCV(svc, param_grid=pram, verbose=3)
svm_grid

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 0.4, 0.6, 1, 3, 100, 200, 500],
                         'gamma': [0.001, 0.1, 0.4, 0.004, 0.003],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [46]:
#svm_grid.fit(x_train,y_train)

In [53]:
#svm_grid.best_params_

In [54]:
svc1 = SVC(kernel='linear')

In [55]:
svc1.fit(x_train,y_train)

SVC(kernel='linear')

In [56]:
svc1.score(x_test,y_test)

0.5614035087719298

### SVR

In [15]:
df=pd.read_csv(r"C:\Users\lenovo\Downloads\dataset\Admission_Predict.csv")

In [16]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

In [17]:
x=df.iloc[:,1:-1]               # X = df.loc[:,'GRE Score':'Research']
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
395        324          110                  3  3.5   3.5  9.04         1
396        325          107                  3  3.0   3.5  9.11         1
397        330          116                  4  5.0   4.5  9.45         1
398        312          103                  3  3.5   4.0  8.78         0
399        333          117                  4  5.0   4.0  9.66         1

[400 rows x 7 columns]

In [18]:
y=df.iloc[:,-1]
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
395    0.82
396    0.84
397    0.91
398    0.67
399    0.95
Name: Chance of Admit , Length: 400, dtype: float64

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.20,random_state=30)

In [20]:
from sklearn.svm import SVR

In [21]:
svr=SVR()

In [22]:
svr.fit(x_train,y_train)        # SVR aren't fit then remove the all null value of the columns

SVR()

In [23]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [24]:
# remove the null value then use for this
# df['column_name'] = df['column_name'].fillina(df['column_name'].mean())     # repleace for mean,median,mode

In [28]:
prid= svr.predict(x_test)
prid

array([0.74771259, 0.56919892, 0.72592885, 0.69061159, 0.66991292,
       0.85099534, 0.7852204 , 0.84740795, 0.67186368, 0.68891074,
       0.87747166, 0.62018896, 0.80125872, 0.82994239, 0.85111114,
       0.75192967, 0.65088063, 0.85667479, 0.7035257 , 0.55303564,
       0.66406718, 0.60384859, 0.63192583, 0.55418237, 0.6126798 ,
       0.53444538, 0.71410874, 0.55746303, 0.84839305, 0.61754225,
       0.87352039, 0.69854446, 0.60283353, 0.78236523, 0.77423106,
       0.58149371, 0.71230224, 0.7677296 , 0.87239871, 0.59803976,
       0.76736709, 0.83457462, 0.77655753, 0.66402985, 0.70415955,
       0.8790552 , 0.75433031, 0.74633518, 0.72870902, 0.81959444,
       0.56058591, 0.74042699, 0.65259726, 0.78959202, 0.66022698,
       0.56958011, 0.7538626 , 0.85029138, 0.745815  , 0.66624669,
       0.77504371, 0.66059951, 0.65812501, 0.75546543, 0.74550546,
       0.7923851 , 0.67841443, 0.79186921, 0.64616159, 0.74320016,
       0.77253858, 0.70876362, 0.64037378, 0.85021118, 0.77336

In [26]:
from sklearn.metrics import r2_score

In [31]:
r2_score(y_test,prid)

0.7110538669026072

In [32]:
df.iloc[0]

Serial No.             1.00
GRE Score            337.00
TOEFL Score          118.00
University Rating      4.00
SOP                    4.50
LOR                    4.50
CGPA                   9.65
Research               1.00
Chance of Admit        0.92
Name: 0, dtype: float64

In [34]:
svr.predict([x.iloc[0]])

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([0.87747166])

In [36]:
svr.score(x_test,y_test)

0.7110538669026072

### Stacking

In [41]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [42]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [43]:
df1=pd.read_csv(r"C:\Users\lenovo\Downloads\dataset\winequality-red.csv")

In [44]:
df1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1591            6.2             0.600         0.08             2.0      0.090   
1592            5.9             0.550         0.10             2.2      0.062   
1593            6.3             0.510         0.13             2.3      0.076   
1594            5.9             0.645         0.12             2.0      0.075   
1595            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1591                 32.0                  44.0  0.99490  3.45       0.58   
1592                 39.0                  51.0  0.99512  3.52       0.76   
1593                 29.0                  40.0  0.99574  3.42       0.75   
1594                 32.0                  44.0  0.99547  3.57       0.71   
1595                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1591     10.5        5  
1592     11.2        6  
1593     11.0        6  
1594     10.2        5  
1595     11.0        6  

[1596 rows x 12 columns]

In [47]:
x=df1.iloc[:,:-1]
y=df1.iloc[:,-1]
print(x)
print(y)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1591            6.2             0.600         0.08             2.0      0.090   
1592            5.9             0.550         0.10             2.2      0.062   
1593            6.3             0.510         0.13             2.3      0.076   
1594            5.9             0.645         0.12             2.0      0.075   
1595            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  

In [75]:
train , val_train ,test , val_test = train_test_split(x,y,test_size= .50, random_state= 30)

In [63]:
x_train, x_test, y_train, y_test =  train_test_split(x,y,test_size= .20, random_state= 30)

In [71]:
# knn alghorithm

In [64]:
knn = KNeighborsClassifier()

In [72]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [66]:
pred = knn.predict(x_test)
pred

array([6, 7, 6, 6, 5, 5, 5, 5, 6, 5, 5, 7, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6,
       6, 6, 5, 6, 5, 7, 5, 5, 4, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 4,
       6, 6, 6, 7, 5, 6, 5, 6, 5, 6, 5, 7, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5,
       5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 7, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6,
       5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 7, 6, 7, 5, 6, 6, 6,
       5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 6, 5, 7, 7, 5, 5, 5, 5, 5,
       7, 6, 6, 6, 5, 6, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6, 7, 5, 5,
       5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 5,
       5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 6, 6, 7, 5, 6, 5, 7, 7, 6, 5, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 7, 6, 6, 6, 5, 5,
       5, 5, 6, 7, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 5,
       5, 5, 5, 6, 6, 5, 7, 5, 6, 6, 5, 5, 5, 5, 6, 7, 6, 5, 6, 6, 5, 6,
       6, 5, 6, 5, 4, 6, 5, 5, 6, 5, 6, 6, 5, 7, 5,

In [67]:
knn.score(x_test,y_test)

0.465625

In [73]:
# svm algorithm

In [68]:
svc =SVC()

In [69]:
svc.fit(x_train, y_train)

SVC()

In [77]:
pred = svc.predict(x_test)
pred

array([6, 6, 5, 6, 5, 5, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 5, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6,
       6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6,
       6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6,
       5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 6,
       6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6,
       6, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6,
       6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5,

In [70]:
svc.score(x_test, y_test)

0.471875

In [80]:
prediction_knn = knn.predict(val_train)
prediction_svc = svc.predict(val_train)

In [81]:
prediction_knn

array([6, 7, 6, 6, 5, 5, 5, 5, 6, 5, 5, 7, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6,
       6, 6, 5, 6, 5, 7, 5, 5, 4, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 4,
       6, 6, 6, 7, 5, 6, 5, 6, 5, 6, 5, 7, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5,
       5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 7, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6,
       5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 7, 6, 7, 5, 6, 6, 6,
       5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 6, 5, 7, 7, 5, 5, 5, 5, 5,
       7, 6, 6, 6, 5, 6, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6, 7, 5, 5,
       5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 5,
       5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 6, 6, 7, 5, 6, 5, 7, 7, 6, 5, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 7, 6, 6, 6, 5, 5,
       5, 5, 6, 7, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 5,
       5, 5, 5, 6, 6, 5, 7, 5, 6, 6, 5, 5, 5, 5, 6, 7, 6, 5, 6, 6, 5, 6,
       6, 5, 6, 5, 4, 6, 5, 5, 6, 5, 6, 6, 5, 7, 5,

In [82]:
prediction_svc

array([6, 6, 5, 6, 5, 5, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 5, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6,
       6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6,
       6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6,
       5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 6,
       6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6,
       6, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6,
       6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5,

In [88]:

input3= np.column_stack((prediction_knn,prediction_svc))

In [89]:
output = val_test

In [90]:
output

1201    7
1074    5
1034    5
511     7
1471    5
       ..
1050    7
200     5
910     7
1103    6
1326    6
Name: quality, Length: 798, dtype: int64

In [94]:
pd.DataFrame(input3)

0  1
0    6  6
1    7  6
2    6  5
3    6  6
4    5  5
..  .. ..
793  7  6
794  5  6
795  7  6
796  6  6
797  6  5

[798 rows x 2 columns]

In [95]:
rf = RandomForestClassifier()

In [96]:
rf.fit(input3,output)

RandomForestClassifier()

In [97]:
rf.score(x_test,y_test)

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


ValueError: X has 11 features, but RandomForestClassifier is expecting 2 features as input.

In [99]:
knn
svc
rf


RandomForestClassifier()

In [101]:
knn_output = knn.predict(x_test)
svc_output = svc.predict(x_test)

In [102]:
output_stack1 = np.column_stack ((knn_output,svc_output))

In [103]:
rf.predict(output_stack1)

array([6, 7, 5, 6, 5, 5, 5, 5, 5, 5, 5, 7, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6,
       6, 6, 5, 6, 5, 7, 5, 5, 4, 5, 5, 5, 5, 5, 5, 6, 6, 5, 5, 6, 5, 4,
       6, 6, 6, 7, 5, 6, 5, 6, 5, 6, 5, 7, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 7, 6, 6,
       5, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6,
       5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 7, 6, 7, 5, 6, 6, 6,
       5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 6, 5, 7, 7, 5, 5, 5, 5, 5,
       7, 6, 6, 6, 5, 6, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6, 7, 5, 5,
       5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 5,
       5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 6, 6, 7, 5, 6, 5, 7, 7, 6, 5, 6, 6,
       5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 7, 6, 6, 6, 5, 5,
       5, 5, 6, 7, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 5,
       5, 5, 5, 6, 6, 5, 7, 5, 6, 6, 5, 5, 5, 5, 6, 7, 5, 5, 6, 6, 5, 6,
       6, 5, 6, 5, 4, 6, 5, 5, 6, 5, 6, 5, 5, 7, 5,

In [104]:
rf.score(output_stack1,y_test)

0.49375