In [1]:
#pip install pandas profiling

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\lenovo\Downloads\dataset\Salary_Data.csv")
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
df.tail()

YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [5]:
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [6]:
from pandas_profiling import ProfileReport
ProfileReport(df)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [17]:
pf=ProfileReport(df)9
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [18]:
pf.to_file('test.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [19]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()

In [12]:
x=df.iloc[:,:-1].values
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [13]:
y=df.iloc[:,-1].values

In [14]:

y                                   # y = mx + c  =  (sales= m*TV + c)

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=21)

In [16]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()

In [17]:
l1.fit(x_train,y_train)

LinearRegression()

In [18]:
l1.intercept_   # intercept is nothing but it is c value

24773.055169267347

In [19]:
l1.coef_               #  it is coefiseant of equation 

array([9424.08936678])

In [20]:
y_pred=l1.predict(x_test)
y_pred.round(2)



array([ 52102.91, 102050.59,  99223.36, 121841.18,  37024.37,  91684.09])

In [21]:
y_test

array([ 56642., 113812., 101302., 122391.,  46205.,  98273.])

In [22]:
file = 'linear_reg.sav'
pickle.dump(l1,open(file,'wb'))

In [23]:
save_model = pickle.load(open(file,'rb'))

In [24]:
save_model.predict([[0.4]])

array([28542.69091598])

In [25]:
l1.score(x_train,y_train)

0.9557540289043546

In [7]:
data=pd.read_csv(r'C:\Users\lenovo\Downloads\dataset\advertising.csv')
data

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [8]:
x=data.iloc[:,:-1]

In [9]:
y=data.iloc[:,-1]

In [10]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(x,y)

LinearRegression()

In [11]:
lm.intercept_                  # y=0.05*TV + 0.10*radio - 0.0003*newspaper + 4.62

4.625124078808655

In [31]:
lm.coef_                 # y= m1x1 +m2x2 + m3x3 + c

array([0.05444578, 0.10700123, 0.00033566])

In [32]:
lm.score(x,y)

0.9025912899684558

In [33]:
import statsmodels.formula.api as smf
lm=smf.ols(formula='Sales ~ TV',data=data).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.812
Model:                            OLS   Adj. R-squared:                  0.811
Method:                 Least Squares   F-statistic:                     856.2
Date:                Sat, 26 Nov 2022   Prob (F-statistic):           7.93e-74
Time:                        17:49:30   Log-Likelihood:                -448.99
No. Observations:                 200   AIC:                             902.0
Df Residuals:                     198   BIC:                             908.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.9748      0.323     21.624      0.000       6.339       7.611
TV             0.0555      0.002     29.260      0.000       0.052       0.059
==============================================================================
Omnibus:                        0.013   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.993   Jarque-Bera (JB):                0.043
Skew:                          -0.018   Prob(JB):                        0.979
Kurtosis:                       2.938   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [34]:
import statsmodels.formula.api as smf
lm=smf.ols(formula='Sales ~ TV+Radio',data=data).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     912.7
Date:                Sat, 26 Nov 2022   Prob (F-statistic):          2.39e-100
Time:                        17:49:31   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             772.7
Df Residuals:                     197   BIC:                             782.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6309      0.290     15.952      0.000       4.058       5.203
TV             0.0544      0.001     39.726      0.000       0.052       0.057
Radio          0.1072      0.008     13.522      0.000       0.092       0.123
==============================================================================
Omnibus:                       16.227   Durbin-Watson:                   2.252
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.973
Skew:                          -0.434   Prob(JB):                     8.43e-07
Kurtosis:                       4.613   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [35]:
import statsmodels.formula.api as smf
lm=smf.ols(formula='Sales ~ TV+Radio+Newspaper',data=data).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     605.4
Date:                Sat, 26 Nov 2022   Prob (F-statistic):           8.13e-99
Time:                        17:49:34   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             774.7
Df Residuals:                     196   BIC:                             787.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6251      0.308     15.041      0.000       4.019       5.232
TV             0.0544      0.001     39.592      0.000       0.052       0.057
Radio          0.1070      0.008     12.604      0.000       0.090       0.124
Newspaper      0.0003      0.006      0.058      0.954      -0.011       0.012
==============================================================================
Omnibus:                       16.081   Durbin-Watson:                   2.251
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.655
Skew:                          -0.431   Prob(JB):                     9.88e-07
Kurtosis:                       4.605   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

## Regularisation :-  
### Lasso , Ridge , Elastic

In [73]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Lasso , Ridge , ElasticNet , ElasticNetCV , LinearRegression , LassoCV, RidgeCV
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import seaborn as sns

In [81]:
data = pd.read_csv(r"C:\Users\lenovo\Downloads\dataset\Admission_Predict.csv")

In [82]:
data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

In [83]:
from pandas_profiling import ProfileReport
df=ProfileReport(data)
df.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [16]:
data['GRE Score']  = data['GRE Score'].fillna(data['GRE Score'].mean())
 
    ###   fill the null value of the #####

In [84]:
data.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

In [85]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         400 non-null    int64  
 1   GRE Score          400 non-null    int64  
 2   TOEFL Score        400 non-null    int64  
 3   University Rating  400 non-null    int64  
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64  
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.2 KB


In [86]:
data.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [87]:
data.drop(columns=['Serial No.'],inplace=True)

### delete the column of dataset ####

In [88]:
x=data.iloc[:,:-1]

In [89]:
y=data.iloc[:,-1]

In [115]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
395        324          110                  3  3.5   3.5  9.04         1
396        325          107                  3  3.0   3.5  9.11         1
397        330          116                  4  5.0   4.5  9.45         1
398        312          103                  3  3.5   4.0  8.78         0
399        333          117                  4  5.0   4.0  9.66         1

[400 rows x 7 columns]

In [117]:
vif_df1=pd.DataFrame()
vif_df1['vif1'] = [variance_inflation_factor(arr,i) for i in range(x.shape[1])]

In [118]:
vif_df1

vif1
0  4.615516
1  4.288959
2  2.919606
3  3.075504
4  2.431258
5  5.207403
6  1.543312

In [91]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
395    0.82
396    0.84
397    0.91
398    0.67
399    0.95
Name: Chance of Admit , Length: 400, dtype: float64

In [92]:
scaler = StandardScaler()

In [93]:
arr=scaler.fit_transform(x)

In [94]:
df1=pd.DataFrame(arr)

In [96]:
df1

0         1         2         3         4         5         6
0    1.762107  1.746971  0.798829  1.093864  1.167321  1.764818  0.909112
1    0.627656 -0.067635  0.798829  0.596653  1.167321  0.455151  0.909112
2   -0.070467 -0.562528 -0.076600 -0.397769  0.052933 -1.005631  0.909112
3    0.453126  0.427257 -0.076600  0.099442 -1.061454  0.119339  0.909112
4   -0.244998 -0.727492 -0.952029 -1.392191 -0.504260 -0.653029 -1.099975
..        ...       ...       ...       ...       ...       ...       ...
395  0.627656  0.427257 -0.076600  0.099442  0.052933  0.740592  0.909112
396  0.714922 -0.067635 -0.076600 -0.397769  0.052933  0.858126  0.909112
397  1.151249  1.417042  0.798829  1.591075  1.167321  1.429006  0.909112
398 -0.419528 -0.727492 -0.076600  0.099442  0.610127  0.304036 -1.099975
399  1.413045  1.582006  0.798829  1.591075  0.610127  1.781609  0.909112

[400 rows x 7 columns]

In [95]:
df1.profile_report()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
df1

0         1         2         3         4         5         6
0    1.762107  1.746971  0.798829  1.093864  1.167321  1.764818  0.909112
1    0.627656 -0.067635  0.798829  0.596653  1.167321  0.455151  0.909112
2   -0.070467 -0.562528 -0.076600 -0.397769  0.052933 -1.005631  0.909112
3    0.453126  0.427257 -0.076600  0.099442 -1.061454  0.119339  0.909112
4   -0.244998 -0.727492 -0.952029 -1.392191 -0.504260 -0.653029 -1.099975
..        ...       ...       ...       ...       ...       ...       ...
395  0.627656  0.427257 -0.076600  0.099442  0.052933  0.740592  0.909112
396  0.714922 -0.067635 -0.076600 -0.397769  0.052933  0.858126  0.909112
397  1.151249  1.417042  0.798829  1.591075  1.167321  1.429006  0.909112
398 -0.419528 -0.727492 -0.076600  0.099442  0.610127  0.304036 -1.099975
399  1.413045  1.582006  0.798829  1.591075  0.610127  1.781609  0.909112

[400 rows x 7 columns]

In [30]:
df1.describe()

0             1             2             3             4  \
count  4.000000e+02  4.000000e+02  4.000000e+02  4.000000e+02  4.000000e+02   
mean  -3.785861e-16  5.412337e-16  7.147061e-16  1.859624e-16 -3.019807e-16   
std    1.001252e+00  1.001252e+00  1.001252e+00  1.001252e+00  1.001252e+00   
min   -2.339367e+00 -2.542098e+00 -1.827457e+00 -2.386613e+00 -2.733036e+00   
25%   -7.685900e-01 -7.274920e-01 -9.520286e-01 -8.949798e-01 -5.042604e-01   
50%    1.679859e-02 -6.763531e-02 -7.660001e-02  9.944220e-02  5.293342e-02   
75%    7.149218e-01  7.571856e-01  7.988286e-01  5.966532e-01  6.101273e-01   
max    2.023903e+00  2.076899e+00  1.674257e+00  1.591075e+00  1.724515e+00   

                  5             6  
count  4.000000e+02  4.000000e+02  
mean   8.076873e-16  2.942091e-17  
std    1.001252e+00  1.001252e+00  
min   -3.020504e+00 -1.099975e+00  
25%   -7.201909e-01 -1.099975e+00  
50%    1.859559e-02  9.091117e-01  
75%    7.783704e-01  9.091117e-01  
max    2.218165e+00  9.091117e-01

In [97]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_df = pd.DataFrame()

In [110]:
arr.shape[1]
print(variance_inflation_factor(arr,1))

4.288959013746899


In [112]:
vif_df['vif'] = [variance_inflation_factor(arr,i) for i in range(arr.shape[1])]


In [101]:
vif_df

vif
0  4.615516
1  4.288959
2  2.919606
3  3.075504
4  2.431258
5  5.207403
6  1.543312

In [123]:
vif_df['feature']  = x.columns
vif_df['vif_df1']  = vif_df1
vif_df.drop(columns=['vif_df1'],inplace=True)

In [124]:
vif_df     ### vif > 10 of the all columns

vif            feature
0  4.615516          GRE Score
1  4.288959        TOEFL Score
2  2.919606  University Rating
3  3.075504                SOP
4  2.431258               LOR 
5  5.207403               CGPA
6  1.543312           Research

In [42]:
arr

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [43]:
x_train, x_test, y_train, y_test = train_test_split(arr,y,test_size=0.25 , random_state=100)

In [44]:
x_train

array([[ 0.01679859, -0.39756367, -0.07660001, ..., -0.50426044,
        -0.06535742, -1.09997489],
       [ 0.62765641,  0.5922214 ,  0.79882862, ..., -0.50426044,
         0.6902197 ,  0.90911166],
       [ 1.41304503,  1.91193482,  1.67425725, ...,  1.16732114,
         1.98309612,  0.90911166],
       ...,
       [-1.03038624, -0.8924562 , -0.95202863, ..., -1.06145431,
        -0.70340033, -1.09997489],
       [-0.50679383, -0.8924562 , -0.07660001, ...,  0.61012728,
         0.0689674 ,  0.90911166],
       [-1.29218245, -0.8924562 , -1.82745726, ..., -2.17584203,
        -1.00563118, -1.09997489]])

In [45]:
lr=LinearRegression()

In [46]:
lr.fit(x_train, y_train)

LinearRegression()

In [47]:
pickle.dump(lr,open('admission_lr_model.pickle','wb'))

In [48]:
lr.predict([[337,118,4,4.5,4.5,9.65,1]])

array([8.80348013])

In [49]:
scaler.transform([[337,118,4,4.5,4.5,9.65,1]])

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[1.76210664, 1.74697064, 0.79882862, 1.09386422, 1.16732114,
        1.76481828, 0.90911166]])

In [50]:
lr.predict([[1.76210664, 1.74697064, 0.79882862, 1.09386422, 1.16732114, 1.76481828, 0.90911166]]).round(2)

array([0.95])

In [51]:
test1 = scaler.transform([[324,107,4,4.0,4.5,8.87,1]])

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [52]:
model1 = pickle.load(open('admission_lr_model.pickle','rb'))

In [53]:
model1.predict(test1)

array([0.80215735])

In [54]:
y_pred = lr.predict(x_test)


In [55]:
## finding the accuracy of the model

In [56]:
## 1)
lr.score(x_test,y_test)          #### R squared 

0.7932671172280984

In [57]:
lr.score(x_train,y_train)

0.8038553086503009

In [58]:
  ### let's create a function to created adjusted R squared
def adj_r2(x,y):
    r2 = lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [59]:
 ## 2)
adj_r2(x_test,y_test)      ### acutual accuracy of the model  

0.7775374413650189

In [60]:
## 3)  y= mx + c
lr.coef_

array([ 0.01395232,  0.02144598,  0.00780718, -0.00911999,  0.0225274 ,
        0.07726781,  0.01248694])

In [61]:
lr.intercept_

0.7212381954918753

## LASSO

In [225]:
lassocv = LassoCV(alphas=None,cv=5, max_iter=20000000, normalize=True)
lassocv.fit(x_train,y_train)

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  warnings.warn(


LassoCV(cv=5, max_iter=20000000, normalize=True)

In [226]:
lassocv.alpha_

0.000194745550886909

In [227]:
lasso = Lasso(alpha = lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=0.000194745550886909)

In [228]:
lasso.score(x_test,y_test)

0.7944741490238062

## Ridge 

In [64]:
ridgecv = RidgeCV(alphas=(0.1, 1.0, 10.0),cv=10, normalize=True)
ridgecv.fit(x_train,y_train)

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from skl

RidgeCV(cv=10, normalize=True)

In [65]:
ridgecv.score(x_test, y_test)

0.8068402121769154

In [66]:
ridgecv.alpha_

0.1

In [235]:
np.random.uniform(0,10,50)

array([5.24878527, 1.22572534, 0.88698005, 2.10212957, 0.0357012 ,
       1.65711485, 2.81584795, 6.69839657, 6.78694878, 8.05216432,
       5.05848122, 3.00489583, 4.40349932, 3.15264261, 6.66291968,
       8.01930292, 3.82631131, 9.07955828, 4.3184425 , 9.97531733,
       9.65575094, 7.25534057, 0.80383626, 8.94157523, 5.60622192,
       0.77727476, 7.22071427, 9.34767663, 0.24591274, 6.93010074,
       9.95078162, 5.88531292, 3.28776873, 2.26084363, 4.80543048,
       4.46522027, 4.53544907, 1.12212431, 4.3374946 , 0.79432269,
       6.09212717, 9.42294597, 2.22566751, 4.30301762, 3.72697523,
       7.31414753, 7.85405982, 0.92464013, 5.34771743, 0.7832244 ])

In [237]:
ridge_lr = Ridge(alpha = ridgecv.alpha_)
ridge_lr.fit(x_train, y_train)

Ridge(alpha=0.1)

In [238]:
ridge_lr.score(x_test, y_test)

0.7933610449221665

## ElasticNet

In [242]:
elastic = ElasticNetCV(alphas=None, cv=10)
elastic.fit(x_train, y_train)

ElasticNetCV(cv=10)

In [243]:
elastic.alpha_

0.0054595619637663574

In [244]:
elastic.l1_ratio

0.5

In [246]:
elastic_lr = ElasticNet(alpha=elastic.alpha_, l1_ratio = elastic.l1_ratio)
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=0.0054595619637663574)

In [247]:
elastic_lr.score(x_test,y_test)

0.8027890071466566

In [126]:
a='shashi'

In [128]:
len(a)

6

In [1]:
dir(dict)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [2]:
len(dir(list))

47

In [4]:
print(list)

<class 'list'>


In [6]:
import numpy as np
array=np.array(dir(dict))

In [8]:
array

array(['__class__', '__class_getitem__', '__contains__', '__delattr__',
       '__delitem__', '__dir__', '__doc__', '__eq__', '__format__',
       '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__',
       '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__',
       '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__',
       '__reduce_ex__', '__repr__', '__reversed__', '__ror__',
       '__setattr__', '__setitem__', '__sizeof__', '__str__',
       '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items',
       'keys', 'pop', 'popitem', 'setdefault', 'update', 'values'],
      dtype='<U17')

In [7]:
array.shape

(45,)

In [ ]:
array

In [ ]:
list

In [9]:
s=[1,5,6,4,8,2,1,4,4,1]


In [17]:
t={}
for i in s:
    if i is not t:
        t.update({i:s.count(i)})
print(t)

{1: 3, 5: 1, 6: 1, 4: 3, 8: 1, 2: 1}


In [40]:
t={}
for i in s:
   
    if i is not t: 
        t.update({i:s.count(i)})
print(t)

{1: 3, 5: 1, 6: 1, 4: 3, 8: 1, 2: 1}


In [13]:
s.count(2)

1

In [41]:
a=[1,2,3,4,5,6,4,5,2,8]
t={}
for i in a:
    if i not in t:
        t.update({i:a.count(i)})
        
        
print(t)

{1: 1, 2: 2, 3: 1, 4: 2, 5: 2, 6: 1, 8: 1}


In [ ]:
n=int(input('Enter the number'))
a,b=0,1
c=()
for i in n:
    c=a+b
    print(c)
    
    
    

In [46]:
##faiboncci series
a,b=0,1
while b < 21:
    s=a+b
    print(s)
    a=b
    b=s
    

1
2
3
5
8
13
21


In [48]:
n=int(input("Enter the number :-"))
a=0
b=1
for i in range(n-2):
    a=b
    b=a+b
    #a=b
    #b=a+b
    print(b)

Enter the number :-10
2
4
8
16
32
64
128
256


In [51]:
### faiboncci series
n=int(input("Enter the number :-"))
x,y=0,1
for i in range(n):
    s=x+y
    print(s)
    x=y
    y=s

Enter the number :-7
1
2
3
5
8
13
21


In [57]:
n='12'
for i in n:   
    print(i,end="\t")
    

1	2	

In [59]:
## pallandrom series
n=input()
if n[::]==n[::-1]:
    print('p')
else:
    print('np')

nitin
p


In [70]:
a='shashikant'
b='rahul'
c=a.join(b)
d=b.join(a)
print(b+a)
print(c)
print(d)

rahulshashikant
rshashikantashashikanthshashikantushashikantl
srahulhrahularahulsrahulhrahulirahulkrahularahulnrahult


In [71]:
b='vijay'
c='sha'
for i in b:
    i=i+c
    print(i)   # or print(i,end='')
 
    

vsha
isha
jsha
asha
ysha


In [74]:
for i in b:
    print(i,end='')
    print(c)     # OR print(c,end='')

rsha
asha
hsha
usha
lsha
