In [1]:
Paragraph = "This is the NLP session that is going on and finally we are happy. iNeuron is a company where we teach all tech"

In [2]:
import nltk

In [3]:
sentence = nltk.sent_tokenize(Paragraph)

In [4]:
## Tokenization
nltk.word_tokenize(Paragraph)

['This',
 'is',
 'the',
 'NLP',
 'session',
 'that',
 'is',
 'going',
 'on',
 'and',
 'finally',
 'we',
 'are',
 'happy',
 '.',
 'iNeuron',
 'is',
 'a',
 'company',
 'where',
 'we',
 'teach',
 'all',
 'tech']

In [5]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [6]:
## Stemming :-
## it is nothin but chenge the mining of the word

stemmer.stem("history")

'histori'

In [7]:
stemmer.stem("organization")

'organ'

In [8]:
stemmer.stem("happy")

'happi'

In [9]:
## Lemmatization
from nltk.stem import WordNetLemmatizer

In [10]:
lemmatizer = WordNetLemmatizer()

In [11]:
lemmatizer.lemmatize("historical")

BadZipFile: File is not a zip file

In [12]:
sentence

['This is the NLP session that is going on and finally we are happy.',
 'iNeuron is a company where we teach all tech']

In [13]:
corpus=[]
for i in range(len(sentence)):
    word=nltk.word_tokenize(sentence[i])
    print(word)
    corpus.append(' '.join(word))

['This', 'is', 'the', 'NLP', 'session', 'that', 'is', 'going', 'on', 'and', 'finally', 'we', 'are', 'happy', '.']
['iNeuron', 'is', 'a', 'company', 'where', 'we', 'teach', 'all', 'tech']


In [14]:
corpus

['This is the NLP session that is going on and finally we are happy .',
 'iNeuron is a company where we teach all tech']

In [15]:
corpu=[]
for i in range(len(sentence)):
    words=nltk.word_tokenize(sentence[i])
    words=[stemmer.stem(word) for word in words]
    print(words)
    corpu.append(' '.join(words))

['thi', 'is', 'the', 'nlp', 'session', 'that', 'is', 'go', 'on', 'and', 'final', 'we', 'are', 'happi', '.']
['ineuron', 'is', 'a', 'compani', 'where', 'we', 'teach', 'all', 'tech']


In [16]:
para = '''
Ratan Naval Tata (born 28 December 1937) is an Indian industrialist and former chairman of Tata Sons. He was also the chairman of the Tata Group from 1990 to 2012, serving also as interim chairman from October 2016 through February 2017. He continues to head its charitable trusts.[2][3] In 2008, he received the Padma Vibhushan, the second highest civilian honour in India, after receiving the Padma Bhushan, the third highest civilian honour in 2000.[4]
'''

In [17]:
para


'\nRatan Naval Tata (born 28 December 1937) is an Indian industrialist and former chairman of Tata Sons. He was also the chairman of the Tata Group from 1990 to 2012, serving also as interim chairman from October 2016 through February 2017. He continues to head its charitable trusts.[2][3] In 2008, he received the Padma Vibhushan, the second highest civilian honour in India, after receiving the Padma Bhushan, the third highest civilian honour in 2000.[4]\n'

In [18]:
sentence = nltk.sent_tokenize(para)

In [19]:
sentence

['\nRatan Naval Tata (born 28 December 1937) is an Indian industrialist and former chairman of Tata Sons.',
 'He was also the chairman of the Tata Group from 1990 to 2012, serving also as interim chairman from October 2016 through February 2017.',
 'He continues to head its charitable trusts.',
 '[2][3] In 2008, he received the Padma Vibhushan, the second highest civilian honour in India, after receiving the Padma Bhushan, the third highest civilian honour in 2000.',
 '[4]']

In [20]:
corpu=[]
for i in range(len(sentence)):
    words=nltk.word_tokenize(sentence[i])
    words=[stemmer.stem(word) for word in words]
    print(words)
    corpu.append(' '.join(words))

['ratan', 'naval', 'tata', '(', 'born', '28', 'decemb', '1937', ')', 'is', 'an', 'indian', 'industrialist', 'and', 'former', 'chairman', 'of', 'tata', 'son', '.']
['he', 'wa', 'also', 'the', 'chairman', 'of', 'the', 'tata', 'group', 'from', '1990', 'to', '2012', ',', 'serv', 'also', 'as', 'interim', 'chairman', 'from', 'octob', '2016', 'through', 'februari', '2017', '.']
['he', 'continu', 'to', 'head', 'it', 'charit', 'trust', '.']
['[', '2', ']', '[', '3', ']', 'in', '2008', ',', 'he', 'receiv', 'the', 'padma', 'vibhushan', ',', 'the', 'second', 'highest', 'civilian', 'honour', 'in', 'india', ',', 'after', 'receiv', 'the', 'padma', 'bhushan', ',', 'the', 'third', 'highest', 'civilian', 'honour', 'in', '2000', '.']
['[', '4', ']']


In [21]:
corpu

['ratan naval tata ( born 28 decemb 1937 ) is an indian industrialist and former chairman of tata son .',
 'he wa also the chairman of the tata group from 1990 to 2012 , serv also as interim chairman from octob 2016 through februari 2017 .',
 'he continu to head it charit trust .',
 '[ 2 ] [ 3 ] in 2008 , he receiv the padma vibhushan , the second highest civilian honour in india , after receiv the padma bhushan , the third highest civilian honour in 2000 .',
 '[ 4 ]']

In [22]:
corpu=[]
for i in range(len(sentence)):
    words=nltk.word_tokenize(sentence[i])
    words=[stemmer.stem(word) for word in words]
    print(words)
    corpu.append(' '.join(words))

['ratan', 'naval', 'tata', '(', 'born', '28', 'decemb', '1937', ')', 'is', 'an', 'indian', 'industrialist', 'and', 'former', 'chairman', 'of', 'tata', 'son', '.']
['he', 'wa', 'also', 'the', 'chairman', 'of', 'the', 'tata', 'group', 'from', '1990', 'to', '2012', ',', 'serv', 'also', 'as', 'interim', 'chairman', 'from', 'octob', '2016', 'through', 'februari', '2017', '.']
['he', 'continu', 'to', 'head', 'it', 'charit', 'trust', '.']
['[', '2', ']', '[', '3', ']', 'in', '2008', ',', 'he', 'receiv', 'the', 'padma', 'vibhushan', ',', 'the', 'second', 'highest', 'civilian', 'honour', 'in', 'india', ',', 'after', 'receiv', 'the', 'padma', 'bhushan', ',', 'the', 'third', 'highest', 'civilian', 'honour', 'in', '2000', '.']
['[', '4', ']']


In [23]:
corpu

['ratan naval tata ( born 28 decemb 1937 ) is an indian industrialist and former chairman of tata son .',
 'he wa also the chairman of the tata group from 1990 to 2012 , serv also as interim chairman from octob 2016 through februari 2017 .',
 'he continu to head it charit trust .',
 '[ 2 ] [ 3 ] in 2008 , he receiv the padma vibhushan , the second highest civilian honour in india , after receiv the padma bhushan , the third highest civilian honour in 2000 .',
 '[ 4 ]']

In [24]:
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


False

In [1]:
!pip install nltk

In [25]:
 from sklearn.feature_extraction.text import CountVectorizer

In [26]:
sentence

['\nRatan Naval Tata (born 28 December 1937) is an Indian industrialist and former chairman of Tata Sons.',
 'He was also the chairman of the Tata Group from 1990 to 2012, serving also as interim chairman from October 2016 through February 2017.',
 'He continues to head its charitable trusts.',
 '[2][3] In 2008, he received the Padma Vibhushan, the second highest civilian honour in India, after receiving the Padma Bhushan, the third highest civilian honour in 2000.',
 '[4]']

In [28]:
import re
corpu=[]
for i in range(len(sentence)):
    text= re.sub('[^a-zA-Z1-9]',' ',sentence[i])
    text=text.lower()
    words=text.split()
    words=[stemmer.stem(word) for word in words]
    print(words)
    corpu.append(' '.join(words))

['ratan', 'naval', 'tata', 'born', '28', 'decemb', '1937', 'is', 'an', 'indian', 'industrialist', 'and', 'former', 'chairman', 'of', 'tata', 'son']
['he', 'wa', 'also', 'the', 'chairman', 'of', 'the', 'tata', 'group', 'from', '199', 'to', '2', '12', 'serv', 'also', 'as', 'interim', 'chairman', 'from', 'octob', '2', '16', 'through', 'februari', '2', '17']
['he', 'continu', 'to', 'head', 'it', 'charit', 'trust']
['2', '3', 'in', '2', '8', 'he', 'receiv', 'the', 'padma', 'vibhushan', 'the', 'second', 'highest', 'civilian', 'honour', 'in', 'india', 'after', 'receiv', 'the', 'padma', 'bhushan', 'the', 'third', 'highest', 'civilian', 'honour', 'in', '2']
['4']


In [30]:
corpu

['ratan naval tata born 28 decemb 1937 is an indian industrialist and former chairman of tata son',
 'he wa also the chairman of the tata group from 199 to 2 12 serv also as interim chairman from octob 2 16 through februari 2 17',
 'he continu to head it charit trust',
 '2 3 in 2 8 he receiv the padma vibhushan the second highest civilian honour in india after receiv the padma bhushan the third highest civilian honour in 2',
 '4']

In [31]:
 from sklearn.feature_extraction.text import CountVectorizer

In [40]:
cv=CountVectorizer(binary=True,ngram_range=(1,2))

In [41]:
cv.fit_transform(corpu)

<5x112 sparse matrix of type '<class 'numpy.int64'>'
	with 120 stored elements in Compressed Sparse Row format>

In [44]:
### applied BOW
cv.fit_transform(corpu).toarray()

array([[0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
        1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        

In [46]:
cv.fit_transform(corpu).toarray().shape

(5, 112)

In [43]:
cv.vocabulary_   ### this is feture index

{'ratan': 81,
 'naval': 71,
 'tata': 90,
 'born': 24,
 '28': 9,
 'decemb': 35,
 '1937': 5,
 'is': 67,
 'an': 16,
 'indian': 61,
 'industrialist': 63,
 'and': 18,
 'former': 39,
 'chairman': 26,
 'of': 75,
 'son': 89,
 'ratan naval': 82,
 'naval tata': 72,
 'tata born': 91,
 'born 28': 25,
 '28 decemb': 10,
 'decemb 1937': 36,
 '1937 is': 6,
 'is an': 68,
 'an indian': 17,
 'indian industrialist': 62,
 'industrialist and': 64,
 'and former': 19,
 'former chairman': 40,
 'chairman of': 28,
 'of tata': 76,
 'tata son': 93,
 'he': 46,
 'wa': 110,
 'also': 13,
 'the': 94,
 'group': 44,
 'from': 41,
 '199': 7,
 'to': 104,
 '12': 0,
 'serv': 87,
 'as': 20,
 'interim': 65,
 'octob': 73,
 '16': 2,
 'through': 102,
 'februari': 37,
 '17': 4,
 'he wa': 49,
 'wa also': 111,
 'also the': 15,
 'the chairman': 95,
 'of the': 77,
 'the tata': 98,
 'tata group': 92,
 'group from': 45,
 'from 199': 42,
 '199 to': 8,
 'to 12': 105,
 '12 serv': 1,
 'serv also': 88,
 'also as': 14,
 'as interim': 21,
 'int

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [48]:
tf_idf=TfidfVectorizer()

In [49]:
tf_idf.fit_transform(corpu).toarray()

array([[0.        , 0.        , 0.        , 0.24321258, 0.        ,
        0.24321258, 0.        , 0.        , 0.24321258, 0.24321258,
        0.        , 0.        , 0.24321258, 0.19622238, 0.        ,
        0.        , 0.        , 0.24321258, 0.        , 0.24321258,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.24321258, 0.24321258,
        0.        , 0.24321258, 0.        , 0.24321258, 0.        ,
        0.19622238, 0.        , 0.24321258, 0.        , 0.        ,
        0.        , 0.24321258, 0.39244476, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.19031713, 0.19031713, 0.19031713, 0.        , 0.19031713,
        0.        , 0.        , 0.38063426, 0.        , 0.        ,
        0.19031713, 0.        , 0.        , 0.30709333, 0.        ,
        0.        , 0.        , 0.        , 0.19031713, 0.        ,
        0.38063426, 0.19031713, 0.1274576 , 0. 

In [52]:
tf_idf.vocabulary_

{'ratan': 37,
 'naval': 33,
 'tata': 42,
 'born': 12,
 '28': 5,
 'decemb': 17,
 '1937': 3,
 'is': 31,
 'an': 8,
 'indian': 28,
 'industrialist': 29,
 'and': 9,
 'former': 19,
 'chairman': 13,
 'of': 35,
 'son': 41,
 'he': 22,
 'wa': 49,
 'also': 7,
 'the': 43,
 'group': 21,
 'from': 20,
 '199': 4,
 'to': 46,
 '12': 0,
 'serv': 40,
 'as': 10,
 'interim': 30,
 'octob': 34,
 '16': 1,
 'through': 45,
 'februari': 18,
 '17': 2,
 'continu': 16,
 'head': 23,
 'it': 32,
 'charit': 14,
 'trust': 47,
 'in': 26,
 'receiv': 38,
 'padma': 36,
 'vibhushan': 48,
 'second': 39,
 'highest': 24,
 'civilian': 15,
 'honour': 25,
 'india': 27,
 'after': 6,
 'bhushan': 11,
 'third': 44}

In [53]:
### new test data
data=["I want to have food"] ## this is word to vect

cv.transform(data).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0]], dtype=int64)